services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: asdesigns_pg
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "asdesigns"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./asdesigns.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge
